import { TypeProduct } from "./utils";

export const products: TypeProduct[] = [
  {
    id: 1,
    name: "Gradient Graphic T-shirt",
    price: 145,
    rating: 4.5,
    image: "/images/products/gradient-graphic-t-shirt.png",
    category: "T-shirts",
  },
  {
    id: 2,
    name: "Polo with Tipping Details",
    price: 180,
    oldPrice: 260,
    rating: 4.8,
    image: "/images/products/polo-with-tipping-details.png",
    category: "Shirts",
  },
  {
    id: 3,
    name: "Black Striped T-shirt",
    price: 120,
    oldPrice: 150,
    rating: 4.2,
    image: "/images/products/black-striped-t-shirt.png",
    category: "T-shirts",
  },
  {
    id: 4,
    name: "Skinny Fit Jeans",
    price: 240,
    oldPrice: 260,
    rating: 4.7,
    image: "/images/products/skinny-fit-jeans.png",
    category: "Jeans",
  },
  {
    id: 5,
    name: "Checkered Shirt",
    price: 180,
    rating: 4.5,
    image: "/images/products/checkerd-shirt.png",
    category: "Shirts",
  },
  {
    id: 6,
    name: "Sleeve Striped T-shirt",
    price: 130,
    oldPrice: 160,
    rating: 4.3,
    image: "/images/products/sleeve-striped-t-shirt.png",
    category: "T-shirts",
  },
  {
    id: 7,
    name: "Vertical Striped Shirt",
    price: 212,
    oldPrice: 232,
    rating: 4.6,
    image: "/images/products/vertical-striped.png",
    category: "Shirts",
  },
  {
    id: 8,
    name: "Courage Graphic T-shirt",
    price: 145,
    rating: 4.4,
    image: "/images/products/courage-graphic.png",
    category: "T-shirts",
  },
  {
    id: 9,
    name: "Loose Fit Bermuda Shorts",
    price: 80,
    oldPrice: 110,
    rating: 4.1,
    image: "/images/products/loose-fit.png",
    category: "Shorts",
  },
  {
    id: 10,
    name: "Faded Skinny Jeans",
    price: 160,
    rating: 4.3,
    image: "/images/products/faded-skinny-jeans.png",
    category: "Pants",
  },
  {
    id: 11,
    name: "One Life Graphic T-shirt",
    price: 220,
    oldPrice: 250,
    rating: 4.6,
    image: "/images/products/one-life-graphic-t-shirt.png",
    category: "Jackets",
  },
  {
    id: 12,
    name: "Polo With Contrast Trim",
    price: 190,
    rating: 4.2,
    image: "/images/products/polo-with-contrast-trim.png",
    category: "Hoodies",
  },
  
];
